apiVersion: v1
kind: Secret
metadata:
  name: termostat-logi-secrets
type: Opaque
data:
  ES_USERNAME: {{ .Values.secrets.ES_USERNAME | b64enc | quote }}
  ES_PASSWORD: {{ .Values.secrets.ES_PASSWORD | b64enc | quote }}
  TUYA_ACCESS_ID: {{ .Values.secrets.TUYA_ACCESS_ID | b64enc | quote }}
  TUYA_ACCESS_KEY: {{ .Values.secrets.TUYA_ACCESS_KEY | b64enc | quote }}
  ES_HOST: {{ .Values.secrets.ES_HOST | b64enc | quote }}
